apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-mod-pvc
  namespace: minecraft-mod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 120Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: minecraft-mod-pv
