apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-staging
spec:
  secretName: letsencrypt-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.tosukui.xyz"
  dnsNames:
  - tosukui.xyz
  - "*.tosukui.xyz"
