apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-production
  namespace: istio-system
spec:
  secretName: letsencrypt-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.tosukui.xyz"
  dnsNames:
  - "*.tosukui.xyz"
