apiVersion: apps/v1
kind: Deployment

metadata:
  name: communitization-bot-deployment
  labels:
    app: communitization-bot

spec:
  selector:
    matchLabels:
      app: bot
  replicas: 0
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: bot
        image: ghcr.io/tosukui/communitization-bot:master
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: api-key

        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bot-info
              key: token
