apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingress
  namespace: httpbin
spec:
  ingressClassName: nginx
  rules:
    - host: httpbin.tosukui.xyz
      http:
        paths:
        - backend:
            service:
              name: httpbin
              port:
                number: 8000
          path: /
          pathType: Prefix
