apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv
  namespace: minecraft
spec:
  capacity:
    storage: 120Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: worker2
    path: /var/nfs/kube/minecraft
