apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      version: v1
  template:
    metadata:
      labels:
        app: mariadb
        version: v1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disk
                operator: In
                values:
                - big
      serviceAccountName: mariadb
      containers:
      - image: mariadb:10.11.7
        imagePullPolicy: IfNotPresent
        name: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: root_password
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mariadb
      volumes:
      - name: mariadb
        persistentVolumeClaim:
          claimName: mariadb-pvc

