apiVersion: v1
kind: Service
metadata:
  name: asari-api
  labels:
    app: asari-api
    service: asari-api
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: asari-api
